sudo: required
services:
  - docker

before_install:
  - docker build -t yum-eats/Customer-Reviews -f Dockerfile.dev .

script:
  - docker run yum-eats/Customer-Reviews npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "Customer-Reviews"
  env: "CustomerReviews-env"
  bucket_name: "elasticbeanstalk-us-west-1-697414267885"
  bucket_path: "Customer-Reviews"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"