sudo: required
services:
  - docker

before_install:
  - docker build -t reviews/test -f ./client/Dockerfile.dev ./client

script:
  - docker run reviews/test npm run test -- --coverage

after_success:
  -docker build -t reviews/client ./client
  -docker build -t reviews/nginx ./nginx 
  -docker build -t reviews/server ./server 
  -docker build -t reviews/database ./database 

  # log in to the dockler cli
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  -docker run reviews/client
  -docker run reviews/nginx
  -docker run reviews/server 
  -docker run reviews/database

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-1"
#   app: "Customer-Reviews"
#   env: "CustomerReviews-env"
#   bucket_name: "elasticbeanstalk-us-west-1-697414267885"
#   bucket_path: "Customer-Reviews"
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"