version: '3'
services: 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      RDS_HOSTNAME: aa10hn2oqnez18.czfipm1dwzy0.us-west-1.rds.amazonaws.com
      RDS_PORT: 3306
      RDS_DB_NAME: yelp
      RDS_USERNAME: alvintan626
      RDS_PASSWORD: studentstudent 

  adminer:
    image: adminer
    restart: always
    ports:
      - 3004:3004

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      -'3004:80'
      
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      RDS_HOSTNAME: aa10hn2oqnez18.czfipm1dwzy0.us-west-1.rds.amazonaws.com
      RDS_PORT: 3306
      RDS_DB_NAME: yelp
      RDS_USERNAME: alvintan626
      RDS_PASSWORD: studentstudent 
